<a href="https://colab.research.google.com/github/Anjal1p/Python-practice/blob/master/DayOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.12.0'

In [0]:
import numpy as np

In [0]:
my_list = [1,2,3]

In [0]:
print(my_list)

[1, 2, 3]


In [0]:
np.array(my_list)

array([1, 2, 3])

In [0]:
my_matrix = [[1,2,3],[4,5,6,],[7,8,9]]

In [0]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
## Built - in methods

**arange**


SyntaxError: ignored

In [0]:
np.arange(0,10)

In [0]:
np.arange(0,11,12)

In [0]:
np.zeros(3)

In [0]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.ones((6,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

1.** Random **

2. array Attributes and Methods

3. Reshaping

4. Indexing and Selection

5. Bunch of pandas

In [0]:
np.linspace(0,13, 3)

array([ 0. ,  6.5, 13. ])

In [0]:
np.random.rand(2)

array([0.26051453, 0.23341487])

In [0]:
np.random.rand(5,5)

array([[0.95634158, 0.80349782, 0.61106331, 0.92075632, 0.36601257],
       [0.15340763, 0.80899262, 0.23620297, 0.2652852 , 0.19406393],
       [0.48130969, 0.11767616, 0.99163168, 0.90349776, 0.37397944],
       [0.07679602, 0.82210613, 0.94925574, 0.75707903, 0.76037297],
       [0.88891665, 0.72678327, 0.1139576 , 0.1427803 , 0.38498579]])

In [0]:
np.random.randint(1,100)

99

In [0]:
np.random.randint(1, 100, 10)

array([45, 83, 56, 87, 19, 81, 97,  8, 90, 25])

**Array Attributes and methods**

Array declaration

arange: create numeric sequences

ranarr: random array

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50, 10)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr

array([ 7, 44, 48, 17, 32,  8, 32, 15, 43, 40])

**Reshape**

Formats the array to be in a matrix format

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
ranarr


array([ 7, 44, 48, 17, 32,  8, 32, 15, 43, 40])

In [0]:
ranarr.max()

48

In [0]:
ranarr.min()

7

**Shaping**

- important while building neural network from scratch

In [0]:
arr.shape

(25,)

In [0]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [0]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [0]:
arr.dtype


dtype('int64')

**Numpy Indexing and Selecting**

take similar array elements

- arr[1:5] - array 1 to 5
- arr[1] - array at index 1

In [0]:
# Create a new array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[8]

8

In [0]:
arr[1:5]

array([1, 2, 3, 4])

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
# Setting all elements of an array to a number
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
# Reset it
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
# index 0 to 6 of the big array
slice_of_arr = arr[0:6]

In [0]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
# Change the array (the change will be shown in the original array as it points to a reference of the original array
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [0]:
# copy of the arr
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])